config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")




  get '/' => 'users#index'
  post '/sessions' => 'sessions#create'
  post '/users' => 'users#create'
  get '/posts' => 'posts#index', as: "home"

  # root "posts#index", as: "home"
  # get "about" => "pages#about", as: "about"

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true,
                        length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @aboutDetail = "Happy new year!";
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
    end

    def show
        @post =Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def create
        # render plain: params[:post].inspect
        @post = Post.new(post_params)
        
        respond_to do |format|
            if (@post.save)
                format.html { redirect_to post_url(@post), notice: 'Post created successfully!' }
                format.json { render :show, status: :created, location: @post }
            else
                format.html { render :new, status: :unprocessable_entity }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

        respond_to do |format|
            if (@post.update(post_params))
                format.html { redirect_to post_url(@post), notice: 'Post updated successfully!' }
                format.json { render :show, status: :created, location: @post }
            else
                format.html { render :edit, status: :unprocessable_entity }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @post = Post.find(params[:id])
        @post.destroy

        respond_to do |format|
            format.html { redirect_to posts_url, notice: 'Post successfully deleted!' }
            format.json { head :no_content }

        end
    end

    private def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def create
        user = User.find_by(email:login_params[:email])
        # if user && user.authenticate(login_params[:password])
        #     session[:user_id] = user.id
        #     redirect_to '/posts'
        # else
        #     flash[:login_errors] = ['Invalid Credentials']
        #     redirect_to '/'
        # end

        respond_to do |format|
            if user && user.authenticate(login_params[:password])
                session[:user_id] = user.id
                format.html { redirect_to '/posts', notice: 'A user successfully logged in!' }
                format.json { render '/posts', status: :logged_in, location: @user }
            else
                format.html { render :index, status: :unprocessable_entity }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    private def login_params
        params.require(:login).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index

    end

    def create
        user = User.new(user_params)

        respond_to do |format|
            if user.save()
                session[:user_id] = user.id
                format.html { redirect_to '/posts', notice: 'Successfully registered new user!' }
                format.json { render :index, status: :created, location: @user }
            else
                format.html { render :index, status: :unprocessable_entity }
                format.json { render json: @user.errors, status: :unprocessable_entity }
            end
        end
    end

    private def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstRubyRailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand">Blog Website</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page"><%= link_to "All blog posts", home_path %></a>
            <a class="nav-link"><%= link_to "Create Post", new_post_path %></a>
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @aboutDetail %></h1>

app/views/posts/_form.html.erb
<%= form_with(model: post)  do |form| %>
    <% if post.errors.any? %>
        <div>
            <% post.errors.full_messages.each do |msg| %>
                <div><%= msg %></div>
            <% end %>
        </div>
    <% end %>
    <p>
        <%= form.label :title %> </br>
        <%= form.text_field :title %>
    </p>

    <p>
        <%= form.label :body %> </br>
        <%= form.text_area :body %>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
    <h2><%= post.title %></h2>
    <h4><%= post.body %></h4>
</div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render "form", post: @post %>

app/views/posts/index.html.erb
<h1>Recent posts:</h1>
</br>
<% @posts.each do |post| %>
    
    <div><%= render post %></div>
    <%= link_to "Read More", post_path(post) %>
    </br>
<% end %>

app/views/posts/new.html.erb
<h1>Create new post</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<div><%= render @post %></div>
<hr>
<%= link_to "Edit", edit_post_path(@post) %>
<%= button_to "Delete", @post, method: :delete %>

app/views/users/index.html.erb
<h1>Login Page</h1>

<form action="/sessions" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="email" name="login[email]" placeholder="email">
    <input type="password" name="login[password]" placeholder="password">
    <input type="submit" name="Create Account">
</form>

<h1>Registration</h1>



<form action="/users" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="name" name="user[name]" placeholder="name">
    <input type="email" name="user[email]" placeholder="email">
    <input type="password" name="user[password]" placeholder="password">
    <input type="password" name="user[password_confirmation]" placeholder="confirm password">
    <input type="submit" name="Create Account">
</form>